* My Personal Website
Find me at [[https://www.westrom.xyz/][https://www.westrom.xyz/]].

I recently rewrote this site in Svelte from ClojureScript.

** Forking
This website is free software, however the content posted within it is not. You may not plagiarize my blog posts.

** Develop
#+begin_src shell
  pnpm dev
#+end_src

*** TODO Figure out a design for this site.

** Release
#+begin_src shell
  pnpm build
#+end_src

** License
West's Personal Website\\
Copyright © 2022 Christian Westrom

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
