# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-node
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore node and Clojure dependency cache.
          keys:
            - 'clj-node-{{ checksum "deps.edn" }}-{{ checksum "package.json" }}'
            # fallback to using the latest cache if no exact match is found
            - 'clj-node'

      - run:
          name: Install node dependencies.
          command: yarn install

      - run:
          name: Run the project
          command: yarn release

      - save_cache:
          name: Save dependency cache.
          paths:
            - ~/.m2
            - ~/.cache/yarn
            - ~/repo/node_modules
          key: 'clj-node-{{ checksum "deps.edn" }}-{{ checksum "package.json" }}'
  deploy:
    docker:
      - image: cimg/base:2021.04
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2f:21:9f:f7:7a:7a:05:2c:e6:d0:21:7f:f2:a4:8d:ba"
      - run:
          name: Deploy with rsync.
          command: |
            echo '[westrom.xyz]:34334 rsa AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAdr/wHib41Sy3nWZg/Yv8p04IjHJHR5+Ph9iH3ojBJ8swLz4TyVNWcpCQx276LQ9gjQsoAaQCyfDT0mlTnApaA= >> ~/.ssh/known_hosts'
            scp -P 34334 -o "StrictHostKeyChecking=no" -r public/* deployer@westrom.xyz:/var/www/westrom.xyz/html/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
#          filters:
#            branches:
#              only: master