# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-node
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn and Clojure Dependency Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
            - yarn-packages-

      - run:
          name: Install Yarn Dependencies
          command: yarn install --immutable

      - run:
          name: Run the project
          command: yarn release

      - save_cache:
          name: Save Yarn Dependency Cache
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - save_cache:
          name: Save Clojure Dependency Cache
          paths:
          - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}

  deploy:
    docker:
      - image: cimg/base
    steps:
      - add_ssh_keys:
          fingerprints:
            - "$RASPI_DEPLOY_SSH_FINGERPRINT"
      - run:
          name: Deploy Over SSH
          command: |
            ssh deployer@westrom.xyz -p $RASPI_DEPLOY_PORT "rm -rf /var/www/westrom.xyz/html/*"
            scp deployer@westrom.xyz -P $RASPI_DEPLOY_PORT -r ~/repo/public/* deployer@westrom.xyz:/var/www/westrom.xyz/html

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master