# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-node
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore node and Clojure dependency cache
          keys:
            - 'clj-node-{{ checksum "deps.edn" }}-{{ checksum "package.json" }}'
            # fallback to using the latest cache if no exact match is found
            - 'clj-node'

      - run:
          name: Install node dependencies
          command: yarn install

      - run:
          name: Run the project
          command: yarn release

      - persist_to_workspace:
         root: ~/
         paths:
          - repo/public

      - save_cache:
          name: Save dependency cache
          paths:
            - ~/.m2
            - ~/.cache/yarn
            - ~/repo/node_modules
          key: 'clj-node-{{ checksum "deps.edn" }}-{{ checksum "package.json" }}'
  deploy:
    docker:
      - image: cimg/base:2021.04
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/repo/public
      - add_ssh_keys:
          fingerprints:
            - "f1:8b:23:49:dd:04:44:48:91:fe:d3:6f:66:b3:91:17"
      - run:
          name: Install rsync
          command: sudo apt update && sudo apt install rsync
      - run:
          name: Deploy via rsync
          command: |
            ssh-keyscan -p 34334 westrom.xyz >> ~/.ssh/known_hosts
            rsync -vzrl --delete-after -e 'ssh -p 34334' --progress ~/repo/public deployer@westrom.xyz:/var/www/westrom.xyz/html
            ssh -p 34334 deployer@westrom.xyz 'chmod -R 755 /var/www/westrom.xyz/html'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
#          filters:
#            branches:
#              only: master