# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-node
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore node and Clojure dependency cache.
          keys:
            - 'clj-node-{{ checksum "deps.edn" }}-{{ checksum "package.json" }}'
            # fallback to using the latest cache if no exact match is found
            - 'clj-node'

      - run:
          name: Install node dependencies.
          command: yarn install

      - run:
          name: Run the project
          command: yarn release

      - save_cache:
          name: Save dependency cache.
          paths:
            - ~/.m2
            - ~/.cache/yarn
            - ~/repo/node_modules
          key: 'clj-node-{{ checksum "deps.edn" }}-{{ checksum "package.json" }}'
  deploy:
    docker:
      - image: cimg/base:2021.04
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "56:e7:b9:61:77:38:dd:88:58:b1:f9:f9:7a:55:fd:e5"
      - run:
          name: Deploy with rsync.
          command: |
            scp -P 34334' -o "StrictHostKeyChecking=no" -r public/* deployer@westrom.xyz:/var/www/westrom.xyz/html/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
#          filters:
#            branches:
#              only: master