(ns app.data)

(def title "My Personal Website")
(def email "c.westrom@westrom.xyz")
(def gitlab "https://gitlab.com/wildwestrom")
(def discord "@West#7965")
(def author "Christian Westrom")
(def year "2021")
(def description "West's Site: A blog, projects, CV, and more.")
(def keywords ["programming" "clojure" "clojurescript" "web development" "javascript"])
