name: Build and Deploy
on: [push, pull_request]

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout

    - name: Setup Node Environment
    - uses: actions/setup-node

    - name: Install pnpm
      uses: pnpm/action-setup

    - name: Cache
      uses: actions/cache
      with:
        path: ${{ env.PNPM_CACHE_FOLDER }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install Dependencies
      run: pnpm deps

    - name: Build
      run: pnpm build
