name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Check style
        run: bun run lint

      - name: Check for errors
        run: bun run check

      - name: Build
        run: bun run build
