name: Build and Deploy
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2

    - name: Cache
      uses: actions/cache@v2

    - name: Install Dependencies
      run: pnpm deps

    - name: Build
      run: pnpm build
